# Generated by Django 3.2.6 on 2021-09-06 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.BooleanField(default=False)),
                ('comp_id', models.IntegerField()),
                ('F_usr', models.IntegerField()),
                ('T_usr', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('data', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='E:\\Study\\SEM 7\\Capstone Project-III\\FSS\\media')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_pic', models.ImageField(blank=True, upload_to='static')),
                ('p_desc', models.CharField(blank=True, max_length=1000)),
                ('own_comp', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
