# Generated by Django 3.2.6 on 2021-10-02 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210926_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='F_usr',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='T_usr',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='comp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
