# Generated by Django 3.2.6 on 2021-10-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211002_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
