# Generated by Django 3.2.6 on 2021-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_chat_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='comp_id',
            new_name='comp_obj',
        ),
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
