# Generated by Django 3.2.6 on 2021-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_chat_f_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='T_usr',
            field=models.BigIntegerField(),
        ),
    ]
