# Generated by Django 3.2.6 on 2021-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_chat_t_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='T_usr',
            field=models.BigIntegerField(null=True),
        ),
    ]
