# Generated by Django 3.2.6 on 2021-10-21 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_chat_t_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='T_usr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 21, 15, 14, 53, 388707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='E:\\Study\\SEM 7\\Capstone Project-III\\FSS\\media'),
        ),
    ]
