# Generated by Django 3.2.6 on 2021-11-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_chat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='F_usr_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='T_usr_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
